# Generated by Django 3.2.5 on 2021-07-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='votingsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=12)),
                ('id_Number', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=8)),
                ('total_voters', models.CharField(max_length=15)),
            ],
        ),
    ]
